eureka:
    client:
        serviceUrl:
            defaultZone: http://${eureka.instance.hostname}:8761/eureka/
    instance:
        hostname: localhost
        prefer-ip-address: true
logging:
    level:
        io:
            seata: info
mybatis:
    mapperLocations: classpath:mapper/*.xml
server:
    port: 8182
spring:
    application:
        name: storage-server
    cloud:
        alibaba:
            seata:
                tx-service-group: my_test_tx_group
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: 111111
        url: jdbc:mysql://localhost:3306/seata_business?serverTimezone=GMT&useUnicode=true&characterEncoding=utf8&useSSL=false
        username: root

