server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 111111
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/seata_business?serverTimezone=GMT&useUnicode=true&characterEncoding=utf8&useSSL=false
  application:
    name: admin-client
mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:SqlMapConfig.xml

